### ISSUE TITLE
Zenbot in Docker Compose with Traefik and redirect to domain. Web GUI offers "Gatway Timeout"!

### ISSUE THREAD

**Issue by FelixSauer** [carlos8f/zenbot#1932]
Helligkeit everybody,
I'm trying to run ZenBot with Docker-Compose from DeviaVir with Traefik.
I edited the Docker-Compose-Traefik.yml, adjusted the labels for Traefik and removed the AdminMongo, because I do not need it.
In the Conf.js I set port to "17356". As recommended on github.

My Docker-compose-traefik.yml
```
version: '3.1'
services:
  zenbotserver:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
      - /app/node_modules/
      - /app/dist/
    restart: always
    tty: true
    expose:
      - "17365"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:zenbot.myhost.de"
      - "traefik.docker.network=zenbot-proxy"
      - "traefik.port=17365"
    networks:
      - internal
      - proxy
    depends_on:
      - mongodb
    environment:
      - MONGODB_PORT_27017_TCP_ADDR=mongodb

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./data/db:/data/db
    command: mongod --bind_ip=0.0.0.0 --logpath=/dev/null
    networks:
      - internal
    expose:
      - 27017

networks:
  proxy:
    external:
      name: "zenbot-proxy"
  internal:
    external: false
```

My Conf.js

```
.
.
.
// output
c.output  = {}

// REST API
c.output.api = {}
c.output.api.on = true
c.output.api.ip = '0.0.0.0' // IPv4 or IPv6 address to listen on, uses all available interfaces if omitted
c.output.api.port = 17365 // 0 = random port, set to 17365 if you use docker

```

Zenbot runs well on the terminal after the build. 
I also can connect to the docker container via "docker exec".
But  when selecting the myHost, on which the Web GUI should run, I get a "Gateway Timeout" from treafik back.

Do I need to add something to the conf.js, so that the output arrives treafik?
Does anyone have any idea?

Thanks so much!
